apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
spec:
  selector: # 尝试选择已经存在在系统中的pod
    matchLabels:
      app: nginx-php
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      serviceAccountName: aliyun
      imagePullSecrets:
        - name: aliyun-secret
      containers:
      # nginx 启动game的container
      - name: nginx-game
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
          readOnly: true
        
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-nginx-conf
          readOnly: true
        - mountPath: /etc/nginx/server.conf
          name: nginx-server-conf
          readOnly: true
        - mountPath: /etc/nginx/fcgi.conf
          name: nginx-fcgi-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/upstream_php-fpm.conf
          name: nginx-conf-d-upstream-php-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/game.conf
          name: nginx-conf-d-game-conf
          readOnly: true
        - mountPath: /logs
          name: log-normal-path

      # nginx中启动manager的container
      - name: nginx-manage
        image: nginx:latest
        ports:
        - containerPort: 81
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
          readOnly: true
        
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-nginx-conf
          readOnly: true
        - mountPath: /etc/nginx/server.conf
          name: nginx-server-conf
          readOnly: true
        - mountPath: /etc/nginx/fcgi.conf
          name: nginx-fcgi-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/upstream_php-fpm.conf
          name: nginx-conf-d-upstream-php-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/manage.conf
          name: nginx-conf-d-manage-conf
          readOnly: true
        - mountPath: /logs
          name: log-normal-path

      # nginx中启动rockmong的container
      - name: nginx-rock-mongo
        image: nginx:latest
        ports:
        - containerPort: 82
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
          readOnly: true
        
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-nginx-conf
          readOnly: true
        - mountPath: /etc/nginx/server.conf
          name: nginx-server-conf
          readOnly: true
        - mountPath: /etc/nginx/fcgi.conf
          name: nginx-fcgi-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/upstream_php-fpm.conf
          name: nginx-conf-d-upstream-php-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/rock-mongo.conf
          name: nginx-conf-d-rock-mongo-conf
          readOnly: true
        - mountPath: /logs
          name: log-normal-path

      # PHP的container
      - name: php-fpm-server
        image: registry.cn-hangzhou.aliyuncs.com/sandstone/php:v-game-1.0.0
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
          readOnly: true
        
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-nginx-conf
          readOnly: true
        - mountPath: /etc/nginx/server.conf
          name: nginx-server-conf
          readOnly: true
        - mountPath: /etc/nginx/fcgi.conf
          name: nginx-fcgi-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/upstream_php-fpm.conf
          name: nginx-conf-d-upstream-php-conf
          readOnly: true
        - mountPath: /etc/nginx/conf.d/manage.conf
          name: nginx-conf-d-manage-conf
          readOnly: true
        - mountPath: /code/game
          name: php-game-code-path
        - mountPath: /code/rock
          name: php-rock-mongo-code-path
        - mountPath: /code/manage
          name: php-manage-code-path
        - mountPath: /logs
          name: log-normal-path
          
      volumes:
      - name: time
        hostPath:
          path: /etc/localtime
      - name: nginx-server-conf
        configMap:
          name: nginx-server-conf
      - name: nginx-nginx-conf
        configMap:
          name: nginx-nginx-conf
      - name: nginx-fcgi-conf
        configMap:
          name: nginx-fcgi-conf
      - name: nginx-conf-d-upstream-php-conf
        configMap:
          name: nginx-conf-d-upstream-php-conf
      - name: nginx-conf-d-game-conf
        configMap:
          name: nginx-conf-d-game-conf
      - name: nginx-conf-d-manage-conf
        configMap:
          name: nginx-conf-d-manage-conf
      - name: nginx-conf-d-rock-mongo-conf
        configMap:
          name: nginx-conf-d-rock-mongo-conf
      - name: php-rock-mongo-code-path
        hostPath:
          path: ../rockmongo-master
      - name: php-game-code-path
        hostPath:
          path: ../gameserver
      - name: php-manage-code-path
        hostPath:
          path: ../manage
      - name: log-normal-path
        hostPath:
          path: /data/cuser00/var/log
