apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  PersistentVolumeClaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /data/cuser00/nfs
    server: 10.70.4.207
