apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-server
  labels:
    name: php-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-server
  template:
    metadata:
      labels:
        app: php-server
    spec:
      serviceAccountName: aliyun
      imagePullSecrets:
        - name: aliyun-secret
      containers:
      - name: php-server
        image: registry.cn-hangzhou.aliyuncs.com/sandstone/php:v-game-1.0.0
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/www/html/
          name: nginx-data
        ports:
        - containerPort: 9000
      volumes:
      - name: nginx-data
        hostPath:
         path: /root/k8s/html
