apiVersion: v1
kind: Service
metadata:
  name: nginx-php
spec:
  type: NodePort
  ports:
  - name: nginx-game
    port: 81
    protocol: TCP
    targetPort: 81
    nodePort: 30081
  - name: nginx-manage
    port: 82
    protocol: TCP
    targetPort: 82
    nodePort: 30082
  - name: nginx-rock-mongo
    port: 83
    protocol: TCP
    targetPort: 83
    nodePort: 30083
  selector:
    app: nginx-php
